matrix:
  arch:
    - 64
    - 32

build:
  image: teaci/msys$$arch
  pull: true
  shell: mingw$$arch
  commands:
    # Run `make check` normally.
    - "mkdir -p m4"
    - "autoreconf -ifv"
    - "CFLAGS='-O3 -g' ./configure"
    - "make -j$(nproc)"
    - "make check -j$(nproc)"
    - "cp -p libmcfgthread.dll.a  libmcfgthread-new.dll.a"
    # Compile and run (?) the sample program.
    ## FIXME: At the moment this crashes on Wine. We must have a REAL Windows to test it.
    ## - ./a
    - "CC=\"gcc\""
    - "CXX=\"g++\""
    - "${CC} -std=c11 test/test.c -lmcfgthread-new -L."
    # Make sure that all `#include` directives in our headers are met.
    - "for cmd in {\"${CC} -x c -std=c99\",\"${CC} -x c -std=c11\",\"${CXX} -x c++ -std=c++98\",\"${CXX} -x c++ -std=c++11\"}; do"
    - "  echo \"Checking #include directives using command:\" $cmd"
    - "  $cmd -Wall -Wextra -Werror `find src -name \"*.h\"` -c /dev/null"
    - "done"

notify:
  irc:
    prefix: " lh_mouse"
    nick: tea-ci
    channel: mcfproj
    server:
      host: chat.freenode.net
      port: 6697
      tls: true
