language: c

os: linux
dist: trusty
sudo: required

addons:
  apt:
    update: true
    packages:
      - mingw-w64-i686-dev
      - mingw-w64-x86-64-dev
      - gcc-mingw-w64-i686
      - gcc-mingw-w64-x86-64
      - g++-mingw-w64-i686
      - g++-mingw-w64-x86-64

env:
  - _arch="i686"
  - _arch="x86_64"

install:
  # Run `make check` normally.
  - CC="${_arch}-w64-mingw32-gcc"
  - mkdir -p m4
  - autoreconf -ifv
  - CFLAGS="-O2 -g -fno-unwind-tables" ./configure --host="${_arch}-w64-mingw32"
  - make -j$(nproc)
  - make check
  - cp -p libmcfgthread.dll.a libmcfgthread-new.dll.a
  - ${CC} -std=c11 test/test.c -lmcfgthread-new -L.
  - ./check_includes.sh

script:
  - exit 0

notifications:
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/#mcfproj"
    template:
      - "[ lh_mouse %{repository_slug}#%{commit}] %{result} on %{branch} by %{author} (%{build_url})"
  email: false
