language: c

os: linux
dist: xenial
sudo: required

addons:
  apt:
    packages:
      - mingw-w64-i686-dev
      - mingw-w64-x86-64-dev
      - gcc-mingw-w64-i686
      - gcc-mingw-w64-x86-64
      - g++-mingw-w64-i686
      - g++-mingw-w64-x86-64

matrix:
  include:
    - env: "_arch=i686"
    - env: "_arch=x86_64"

before_install:
  - "test -n \"${CC}\" && unset CC"

install:
  # Run `make check` normally.
  - "mkdir -p m4"
  - "autoreconf -ifv"
  - "CFLAGS='-O3 -g -fno-unwind-tables' ./configure --host=\"${_arch}-w64-mingw32\""
  - "make -j$(nproc)"
  - "make check"
  - "cp -p libmcfgthread.dll.a  libmcfgthread-new.dll.a"
  - "CC=\"${_arch}-w64-mingw32-gcc\""
  - "CXX=\"${_arch}-w64-mingw32-g++\""
  - "${CC} -std=c11 test/test.c -lmcfgthread-new -L."
  # Make sure that all `#include` directives in our headers are met.
  - |
    for cmd in {"${CC} -x c -std=c99","${CC} -x c -std=c11","${CXX} -x c++ -std=c++98","${CXX} -x c++ -std=c++11"}; do
      echo "Checking #include directives using command:" $cmd
      $cmd -Wall -Wextra -Werror `find src -name "*.h"` -c /dev/null
    done

script:
  - "exit 0"

notifications:
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/#mcfproj"
    template:
      - "[ lh_mouse %{repository_slug}#%{commit}] %{result} on %{branch} by %{author} (%{build_url})"
  email: false
