language: c

os: linux
dist: trusty
sudo: required

matrix:
  include:
    - env: "_arch=i686"
    - env: "_arch=x86_64"

before_install:
  - "sudo apt-get -qq update"
  - "_pkgarch=$(echo \"${_arch}\" | sed \"s/[^a-zA-Z0-9]/-/g\")"
  - "sudo apt-get install -y \"gcc-mingw-w64-${_pkgarch}\" \"mingw-w64-${_pkgarch}-dev\""
  - test -n "${CC}" && unset CC

install:
  # Run `make distcheck` normally.
  - "mkdir -p m4"
  - "autoreconf -ifv"
  - "CFLAGS='-O3 -g -fno-exceptions' ./configure --host=\"${_arch}-w64-mingw32\""
  - "make -j$(nproc)"
  - "make distcheck -j$(nproc)"
  - "cp -p libmcfgthread.dll.a  libmcfgthread-new.dll.a"
  - "${_host}-gcc test/test.c -lmcfgthread-new -L."
  # Make sure that all `#include` directives in our headers are met.
  - "for cmd in {\"${_host}-gcc -x c -std=c99\",\"${_host}-gcc -x c -std=c11\",\"g++ -x c++ -std=c++98\",\"g++ -x c++ -std=c++11\"}; do"
  - "  echo \"Checking #include directives using command:\" $cmd"
  - "  $cmd -Wall -Wextra -Werror `find src -name \"*.h\"` -c /dev/null"
  - "done"

notifications:
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/#mcfproj"
    template:
      - "[ lh_mouse %{repository_slug}#%{commit}] %{result} (%{build_url})"
